version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: wipro_jpa     
      MYSQL_USER: devuser             
      MYSQL_PASSWORD: devpass      
      MYSQL_ROOT_PASSWORD: rootpass 
    ports:
      - "3307:3306"                     
    volumes:
      - mysql-data:/var/lib/mysql 

  app:
    build: .
    container_name: my-springboot-app-2
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wipro_jpa
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8081:8082"   

volumes:
  mysql-data:
